export const POPULAR_MOVIES_REQUEST = "POPULAR_MOVIES_REQUEST";
export const POPULAR_MOVIES_SUCCESS = "POPULAR_MOVIES_SUCCESS";
export const POPULAR_MOVIES_FAILURE = "POPULAR_MOVIES_FAILURE";

export const TRENDING_MOVIES_REQUEST = "TRENDING_MOVIES_REQUEST";
export const TRENDING_MOVIES_SUCCESS = "TRENDING_MOVIES_SUCCESS";
export const TRENDING_MOVIES_FAILURE = "TRENDING_MOVIES_FAILURE";
