export const POPULAR_MOVIES_REQUEST = "POPULAR_MOVIES_REQUEST";
export const POPULAR_MOVIES_SUCCESS = "POPULAR_MOVIES_SUCCESS";
export const POPULAR_MOVIES_FAILURE = "POPULAR_MOVIES_FAILURE";

export const TRENDING_GET_REQUEST = "TRENDING_GET_REQUEST";
export const TRENDING_GET_SUCCESS = "TRENDING_GET_SUCCESS";
export const TRENDING_GET_FAILURE = "TRENDING_GET_FAILURE";
