// Movies Actions
export const POPULAR_MOVIES_REQUEST = "POPULAR_MOVIES_REQUEST";
export const POPULAR_MOVIES_SUCCESS = "POPULAR_MOVIES_SUCCESS";
export const POPULAR_MOVIES_FAILURE = "POPULAR_MOVIES_FAILURE";
export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILURE = "MOVIE_DETAILS_FAILURE";
export const MOVIE_CREDITS_REQUEST = "MOVIE_CREDITS_REQUEST";
export const MOVIE_CREDITS_SUCCESS = "MOVIE_CREDITS_SUCCESS";
export const MOVIE_CREDITS_FAILURE = "MOVIE_CREDITS_FAILURE";

// Trending Actions
export const TRENDING_GET_REQUEST = "TRENDING_GET_REQUEST";
export const TRENDING_GET_SUCCESS = "TRENDING_GET_SUCCESS";
export const TRENDING_GET_FAILURE = "TRENDING_GET_FAILURE";

// Search Actions
export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";

// People Actions
export const PERSON_GET_REQUEST = "PERSON_GET_REQUEST";
export const PERSON_GET_SUCCESS = "PERSON_GET_SUCCESS";
export const PERSON_GET_FAILURE = "PERSON_GET_FAILURE";
